#THIS FILE STOCK ALL VARIALBE 
marques     = [
    "ABUS","BOSCH","BOSTIK","brennenstuhl","CEBA","DELTA-PLUS","DIADORA","DIAGER","DIAM-INDUSTRIES",
    "EDMA","FISCHER","GYS","Hikoki-Hitachi","KARCHER","KS-TOOLS","KNIPEX","L-OUTIL-PARFAIT","LMA","MAKITA",
    "MILWAUKEE","PMS-INDUSTRIE","SCELL-IT","SIDAMO","SOPPEC","STANLEY","VIRAX","WD-40"
    ]
